FinfPaws
SerejS/wise-task-algorithms-2024 pull request #7
Opened 2024-05-22 17:18 UTC by radim601

2024-05-25 20:04 UTC, Arttish requested changes

2024-05-25 20:04 UTC, Arttish commented on wise-task-algorithms-2024-paws/.idea/.gitignore
Удалить .idea

2024-05-25 20:04 UTC, Arttish commented on wise-task-algorithms-2024-paws/math-system-1_0-SNAPSHOT.jar
Убрать все бинарники

2024-05-25 20:04 UTC, Arttish commented on wise-task-algorithms-2024-paws/FindPaws/out/artifacts/FindPaws/FindPaws.jar
Убрать все бинарники

2024-05-25 20:04 UTC, Arttish commented on wise-task-algorithms-2024-paws/FindPaws/target/classes/FindPaws.class
Убрать все бинарники

2024-05-25 20:04 UTC, Arttish commented on wise-task-algorithms-2024-paws/FindPaws/target/classes/paw.class
Убрать все бинарники

2024-05-25 20:04 UTC, Arttish commented on wise-task-algorithms-2024-paws/FindPaws/target/test-classes/FindPawsTest.class
Убрать все бинарники

2024-05-26 07:02 UTC, SerejS commented on wise-task-algorithms-2024-paws/math-system-1_0-SNAPSHOT.jar
Однако jar-файл, который требуется по гайду все же следует оставить.

2024-05-26 07:03 UTC, SerejS commented on wise-task-algorithms-2024-paws/FindPaws/target/classes/FindPaws.class
Более точно, скорее убрать директорию target и её содержимое.

2024-05-28 19:22 UTC, Arttish requested changes

2024-05-28 19:22 UTC, Arttish commented on wise-task-algorithms-2024-paws/math-system-1_0-SNAPSHOT.jar
Но этот как раз не требуется

2024-05-29 18:42 UTC, Arttish approved these changes

2024-05-29 18:42 UTC, merged